services:
  database:
    image: postgres:16.2-alpine
    ports:
      - '${DB_PORT}:${DB_PORT}'
    restart: unless-stopped
    volumes:
      - .postgres-data/:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 2000M
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    depends_on:
      - database
    ports:
      - '${PORT}:${PORT}'
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/.postgres-data/
      - /app/node_modules/
    deploy:
      resources:
        limits:
          memory: 2000M
